### PR TITLE
Add automatic publish workflow on release #26

### LINKED ISSUE #26: Implement Proper Release Workflow with Git Tags
While our development process has been progressing smoothly, it's crucial to invest time in establishing a more formal release workflow. Currently, we lack a standardized approach to versioning and release management, which can lead to challenges in tracking changes and coordinating releases. Implementing a proper release workflow, including the use of Git tags, will contribute to a more organized and transparent development process.

Implementation Steps:

Release Workflow w\ Git Tags:
- Define a standardized release process that includes versioning, changelogs, and pre-release testing.
- Document the release process and guidelines for versioning in the project documentation.
- Integrate the use of Git tags into the release process and ensure that each release is tagged with the corresponding version number.

### PR DESCRIPTION
**Pull request by MarcoHuebner**
Triggers on published release, independent from a git tag. Requires a hand-made release, which we will keep for now to be able to fully customize the release note content.

~TODO: Investigate secrets and variables (security) to enable globally consistent python and poetry workflow versions~

Resolves #26

### CODE REVIEW

**Comment by MarcoHuebner** [comment]
Added global repository variables in workflows: `vars.PYTHON_VERSION` (should point to "3.10") and `vars.POETRY_VERSION` (should point to "1.6.1")

**Comment by pmayd** [comment]
So I have to create these env vars correct?

**Comment by pmayd** [comment]
I created the repository env vars that should be available now with `vars.X`: 
image

**Comment by pmayd** [comment]
I rerun the pipeline and all jobs are green again!

**Comment by MarcoHuebner** [comment]
Thanks a lot! Can be merged

**Pull request merged**
